### PR TITLE
Add fma

### PR DESCRIPTION
**Pull request by haampie**
I'm counting an fused-multiply-add as a single flop. I'm not sure what people do in literature (1 or 2 flops), but  as I see it it is a single fused instruction, so 1 flop.

### CODE REVIEW

**Comment by chriselrod** [comment]
When FLOPS of things like `gemm`, it's considered 2 ops.
Many architectures don't have fma, and some algorithms don't let you or make it hard to fuse.

**Comment by haampie** [comment]
Hm yeah, I could make it count as 2 flops. What does @ffevotte think?

**Comment by haampie** [comment]
It now counts an fma as 2 flops, but I'm sticking to counting function calls in the accumulator object, so the factor 2 shows up in the `flop` function now.

**Comment by ffevotte** [comment]
Thanks for this!

I like the middle ground of having `@count_ops` easy to understand (one op per FMA), but counting 2 FLOPs in a way that is consistent with `peakflops` & co...

I added a mention about this in the README (in https://github.com/triscale-innov/GFlops.jl/tree/add-fma), and will merge this as soon as CI passes.

Thanks again!

**Pull request merged**
