### PR TITLE
Widen compat bounds, bump version

### PR DESCRIPTION
**Pull request by charleskawczynski**
Hello, and thanks for the great package! This PR widens the compat bounds so that users can upgrade to newer versions.

This passes all the tests for me with julia 1.7 and 1.8

### CODE REVIEW

**Comment by tristanmontoya** [comment]
The conflict with PrettyTables is preventing me from using the latest version of PrettyTables in my package [StableSpectralElements.jl](https://github.com/tristanmontoya/StableSpectralElements.jl). Would someone (@ffevotte?) be willing to review and merge this PR? Thanks so much!

**Comment by ffevotte** [comment]
Yes, I'm very sorry about not taking proper care of the package in the past few months. Unfortunately it looks like some things have broken for Julia 1.9+
Let me check what happens a bit more thoroughly; hopefully I'll have something working soon. Please feel free to ping me if you don't see anything coming by the end of August.

**Comment by ffevotte** [comment]
Thanks a lot @charleskawczynski for this PR! I took the liberty of rebasing it in #46, in which I also introduced a few changes:
- I think it is incorrect to widen the compat bounds for `Cassette`; as far as I recall, versions 0.3.0 & 0.3.1 really aren't compatible with `GFlops`
- I simplified a bit the code handling `PrettyTables`: I don't think it is necessary to be able to support versions 1 & 2 simultaneously, so `GFlops.jl` v0.1.7 only declares compatibility with `PrettyTables` v2.

@tristanmontoya does this work for you?

In any case, I'm going to close this PR, considering that it is superseded by #46, but if any of you feel like I missed something, please do not hesitate to re-open it.

Thanks again!

**Comment by tristanmontoya** [comment]
@ffevotte thanks so much - it works for me!

**Comment by charleskawczynski** [comment]
Hi @ffevotte, sounds good to me, and thanks for getting that merged! Are you planning to eventually update Cassette?

**Comment by ffevotte** [comment]
Hi @charleskawczynski 

Do you have a specific `Cassette` version in mind? Currently, it looks like installing `GFlops` in a fresh environment results in bringing `Cassette` v0.3.12 as a dependency. Which I think is the latest released version... Or did I miss something?

**Comment by charleskawczynski** [comment]
Ah, yes, the latest one. I just realized the previous compat should be fine for updating. All is well, thanks again!

**Pull request closed without merging**
